[[shows]]
name = "Up First from NPR"
spotify_show_id = "2mTUnDkuKUkhiueKcVWoP0"
pin_slot = 1
mode = "latest_only"

[[shows]]
name = "BirdNote Daily"
spotify_show_id = "6jQh9jTz81rZzv7WwrtiAi"
pin_slot = 2
mode = "latest_only"

[[shows]]
name = "Flying New Guy"
spotify_show_id = "4XQyGRnBcNrvmXwfP13pKH"
pin_slot = 2
mode = "sequential"

[[shows]]
name = "Your Flight Controls"
spotify_show_id = "2lpkNsxnYVpAuM0Nf7i4aV"
pin_slot = 2
mode = "sequential"

[[shows]]
name = "PPL Audio Ground School podcast - VIP"
spotify_show_id = "3y5og4teOjQik9lVv94ZkH"
pin_slot = 2
mode = "sequential"

[[shows]]
name = "Behind the Prop"
spotify_show_id = "489dSSpkhUlVZCt5Zd2vsI"
pin_slot = 2
mode = "sequential"

[[shows]]
name = "The Daily"
spotify_show_id = "3IM0lmZxpFAY7CwMuv9H4g"
pin_slot = 3
mode = "latest_only"

[[shows]]
name = "30 for 30 Podcasts"
spotify_show_id = "3nZo0GuEfiOMacTbOb2ESE"

[[shows]]
name = "99% Invisible"
spotify_show_id = "2VRS1IJCTn2Nlkg33ZVfkM"

[[shows]]
name = "A Bootiful Podcast"
spotify_show_id = "5eyimRNrvZStATQk8by82A"

[[shows]]
name = "ABCs of Parenting Adult Children"
spotify_show_id = "23acQu8UkkKLr8ImfN52ln"

[[shows]]
name = "airhacks.fm podcast with adam bien"
spotify_show_id = "6nOTQLa2uZxeyGpMW8eppS"

[[shows]]
name = "Broken Ground"
spotify_show_id = "4BOMSR1qHT7vt3nCsFnF3G"

[[shows]]
name = "CaSE: Conversations about Software Engineering"
spotify_show_id = "5KRybj1mOAcVNaho9s7jCi"

[[shows]]
name = "Comedy Bang Bang: The Podcast"
spotify_show_id = "1tnKU0o0aXq2iGHdMy44jm"

[[shows]]
name = "Criminal"
spotify_show_id = "3ictIqfumbmEuWdt9xWQp5"

[[shows]]
name = "Dan Carlin's Hardcore History"
spotify_show_id = "72qiPaoDRf8HkGKEChvG5q"

[[shows]]
name = "Effective Engineering Manager"
spotify_show_id = "3s3B19HpeQLrSOalA0rmGo"

[[shows]]
name = "Euphomet"
spotify_show_id = "5mBzQzxlXO121OIcjCvv0F"

[[shows]]
name = "Fall of Civilizations Podcast"
spotify_show_id = "44DE64rRpX1cFIQUlqQtvi"

[[shows]]
name = "Flightless Bird"
spotify_show_id = "0TY5qJWU2bH9DSX9Gsx8VN"

[[shows]]
name = "FoundMyFitness"
spotify_show_id = "5QjpaU0o1Q2MkVZwwG3y7d"

[[shows]]
name = "Freakonomics Radio"
spotify_show_id = "6z4NLXyHPga1UmSJsPK7G1"

[[shows]]
name = "Full Stack Radio"
spotify_show_id = "0Ddvex5OtYOvhyyK6ckG3A"

[[shows]]
name = "GD POLITICS"
spotify_show_id = "3XUkLfwsKGL1n7DF2tbyQS"
mode = "latest_only"

[[shows]]
name = "GOTO - The Brightest Minds in Tech"
spotify_show_id = "1X1lCb4auIZoQKyYiC2PYM"

[[shows]]
name = "Happy Path Programming"
spotify_show_id = "25XAbgCB7VeHgREPSUzBYY"

[[shows]]
name = "Home Cooking"
spotify_show_id = "1K6SiDxdGacAmhMQIvdJUL"

[[shows]]
name = "Home of the Brave"
spotify_show_id = "0VNylaQQ2L0DiPoaDAax7k"

[[shows]]
name = "Huberman Lab"
spotify_show_id = "79CkJF3UJTHFV8Dse3Oy0P"

[[shows]]
name = "In Our Headphones"
spotify_show_id = "5g9S5OSGCduou3Ufn3Tz5i"

[[shows]]
name = "Inside Java"
spotify_show_id = "434ZpirtxvKZmW3yWICCsR"

[[shows]]
name = "Invisibilia"
spotify_show_id = "1Tgsr2BDHLSQ44YsOwoguj"

[[shows]]
name = "Java Off-Heap"
spotify_show_id = "6uHXDdtXmcsWZWhIOWkHsF"

[[shows]]
name = "Let's Talk About Myths, Baby! | Greek Mythology & the Ancient Mediterranean"
spotify_show_id = "6S9jAhlyZtr5dj2tqYXeJ6"

[[shows]]
name = "Live From Don't Tell Comedy"
spotify_show_id = "78sw99DhVbbNg3g1MGCeSM"

[[shows]]
name = "Magic Mics Podcast"
spotify_show_id = "35p9JGGXN973O1Nn7G4J8d"
mode = "latest_only"

[[shows]]
name = "Master Plan"
spotify_show_id = "53PK9UJVE1keigtCX5BkRZ"

[[shows]]
name = "Mike Birbiglia's Working It Out"
spotify_show_id = "2ux2xJbEpqls09oSD1LUHI"

[[shows]]
name = "MIT Supply Chain Frontiers"
spotify_show_id = "6kUFt2eTqRk0uOFAQc3jOb"

[[shows]]
name = "Nature is the Solution"
spotify_show_id = "43bWgkIaH36IYEvXuZ67bS"

[[shows]]
name = "Netflix Is A Daily Joke"
spotify_show_id = "0e2HFBiiGl9hMjZsk4WIvW"

[[shows]]
name = "No Such Thing As A Fish"
spotify_show_id = "4pqW0HTIeZcx7vqHpwzmZj"

[[shows]]
name = "Note to Self"
spotify_show_id = "4kwUFLq1kXZeji9IVYDIUz"

[[shows]]
name = "NPR Music"
spotify_show_id = "10LYbliXlNZe1VStsTkcC0"

[[shows]]
name = "NPR News Now"
spotify_show_id = "6BRSvIBNQnB68GuoXJRCnQ"
mode = "latest_only"

[[shows]]
name = "Ologies with Alie Ward"
spotify_show_id = "5nvRkVMH58SelKZYZFZx1S"

[[shows]]
name = "Pale Blue Pod"
spotify_show_id = "7n5aWCRPax1U5ZdVhkHqB4"

[[shows]]
name = "Paper Trail"
spotify_show_id = "0zdWwklZwPBY7YCX5GIFRH"

[[shows]]
name = "Particles of Thought"
spotify_show_id = "643AlboIMnQgdvFMjJ1V01"

[[shows]]
name = "Programming Throwdown"
spotify_show_id = "274Z0vXSCYxddYGj2hLJ8r"

[[shows]]
name = "Radiolab"
spotify_show_id = "2hmkzUtix0qTqvtpPcMzEL"

[[shows]]
name = "REWORK"
spotify_show_id = "5JxcIaIkN8zx3Zy7yD9snv"

[[shows]]
name = "Risky Business with Nate Silver and Maria Konnikova"
spotify_show_id = "1kEQxTvQ7PUTUmvjcJrpwZ"

[[shows]]
name = "Science Vs"
spotify_show_id = "5lY4b5PGOvMuOYOjOVEcb9"

[[shows]]
name = "SmartLess"
spotify_show_id = "0Yzd0g8NYmn27k2HFNplv7"

[[shows]]
name = "Soft Skills Engineering"
spotify_show_id = "59I1XnvAB9fQzSj9SIKCoI"

[[shows]]
name = "Software Engineering Daily"
spotify_show_id = "6UCtBYL29hwhw4YbTdX83N"

[[shows]]
name = "Software Engineering Radio - the podcast for professional software developers"
spotify_show_id = "6UO3XQclSuNnGxB39QdAnL"

[[shows]]
name = "StaffEng"
spotify_show_id = "4GUCKSlaFqQiShJBOP4nEe"

[[shows]]
name = "The Allusionist"
spotify_show_id = "7sQ5gz1B7kWT9VxCHVRq4D"

[[shows]]
name = "The Daily Stoic"
spotify_show_id = "7fY99FB3bNyn7nEdXCoBeB"

[[shows]]
name = "The InfoQ Podcast"
spotify_show_id = "4NhWaYYpPWgWRDAOqeRQbj"

[[shows]]
name = "The Inquiry"
spotify_show_id = "6kkyreLXgOD3tuizoTYW1N"

[[shows]]
name = "The Pragmatic Engineer"
spotify_show_id = "2Bho9xCbOQMWMJ7UKmqCzD"

[[shows]]
name = "The Science of Birds"
spotify_show_id = "5RKmlf4wdgocsIr6zEGJ2c"

[[shows]]
name = "The Tim Ferriss Show"
spotify_show_id = "5qSUyCrk9KR69lEiXbjwXM"

[[shows]]
name = "The Weekly Show with Jon Stewart"
spotify_show_id = "0sxpFsg449GC8TPtrRVCUW"

[[shows]]
name = "Theoretically Speaking"
spotify_show_id = "3sBBPfPH2QX077NxfTNeSD"

[[shows]]
name = "This American Life"
spotify_show_id = "41zWZdWCpVQrKj7ykQnXRc"

[[shows]]
name = "This Day in AI Podcast"
spotify_show_id = "6qk8KB3SzVw14vuKneLG8o"

[[shows]]
name = "Thriving Kids"
spotify_show_id = "7Knas1fk859Vul6SuOTk3Z"

[[shows]]
name = "Throughline"
spotify_show_id = "0vYTIMav7el5VXq5n5pxhI"

[[shows]]
name = "Today, Explained"
spotify_show_id = "3pXx5SXzXwJxnf4A5pWN2A"

[[shows]]
name = "Twenty Thousand Hertz"
spotify_show_id = "4E8CLD9KUvrwNPjTP4WGrf"

[[shows]]
name = "Two's Complement"
spotify_show_id = "52irDllU36Y3mOBbBIxyNd"

[[shows]]
name = "What to Carry, What to Burn"
spotify_show_id = "4L7FCFQLcmG2NwPw7ayE1D"

[[shows]]
name = "When Science Finds a Way"
spotify_show_id = "08ZFj7rWmEHhok55noveqM"

[[shows]]
name = "Wild Bird Acoustics"
spotify_show_id = "7gnnTqQjOeEFlQB8dk5bkA"

[[shows]]
name = "World of Sharks"
spotify_show_id = "464Xkx160AJUvaov7osKtY"

[[shows]]
name = "You know, for search, an Elastic podcast"
spotify_show_id = "6DLhSV2P7aBQemyUcTVZKE"
